# Generated by Django 4.0.1 on 2022-01-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productimages_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='image',
            new_name='cover_image',
        ),
    ]
