# Generated by Django 3.2 on 2022-02-12 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220212_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('Blog_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BlogCategory', to='blog.blogcategory')),
            ],
        ),
    ]
