# Generated by Django 3.2 on 2022-02-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_blog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
