# Generated by Django 3.2 on 2022-02-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
