# Generated by Django 4.0.2 on 2022-02-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.ImageField(default='CustomerProfilePic/default.jpg', upload_to='media/CustomerProfilePic/'),
        ),
    ]
