# Generated by Django 4.0.2 on 2022-02-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_alter_userprofile_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.ImageField(default='CustomerProfilePic/default.jpg', upload_to='CustomerProfilePic/'),
        ),
    ]
