# Generated by Django 4.0.2 on 2022-02-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_alter_userprofile_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
    ]
