# Generated by Django 4.0.2 on 2022-02-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_alter_userprofile_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=None, help_text='Email', max_length=254),
            preserve_default=False,
        ),
    ]
