# Generated by Django 4.0.2 on 2022-02-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0025_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.ImageField(blank=True, default='media/img/profile-img.jpg', null=True, upload_to='media'),
        ),
    ]
