# Generated by Django 4.0.2 on 2022-02-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_coupan_name_couponcode_coupon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
