# Generated by Django 4.0.2 on 2022-03-03 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 18, 8, 45, 371168)),
        ),
    ]
