# Generated by Django 4.0.2 on 2022-03-03 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
